---
- name: My first play to copy files
  become: true
  hosts: 45.77.42.163
  connection: remote
  remote_user: subramanya
  sudo: true
  tasks:

    - name: Example copying file with owner and permissions
      copy:
        remote_src: /home/ftphome/*
        remote_dest: /etc/ftphome
        owner: pinnacleftp
        group: pinnacleftp
        








