---

- name: My first play to copy files
  become: true
  hosts: 45.77.42.163
  connection: remote
      tasks:

      copy:
        remote_src: /home/ftphome/*
        remote_dest: /etc/ftphome
        owner: pinnacleftp
        group: pinnacleftp
        








